### ISSUE TITLE
Issue with expo@52

### ISSUE THREAD

**Issue by fredle09** [roninoss/create-expo-stack#430] opened 2024-11-14 16:46 UTC
## Steps to Reproduce

1. `npx create-expo-stack`
2. name the project -> ... -> `Expo Router` -> `Drawer + Tabs` -> `NativeWind` ->  ...

Error updating packages:
```
{
  "stdout":
    "Skipped fixing dependencies: react-native-safe-area-context. These dependencies are listed in expo.install.exclude in package.json. Learn more: https://docs.expo.dev/more/expo-cli/#configuring-dependency-validation
    Skipped checking expo-router dependencies: expo-router/doctor.js not found.
    › Installing 14 SDK 52.0.0 compatible native modules using npm
    > npm install",
  "status":null,
  "error":
  {
    "code": "ENOENT",
    "errno": "ENOENT",
    "syscall": "spawn cd",
    "path": "cd",
    "spawnargs": ["<project-name>", "&&", "npx", "expo@latest", "install", "--fix"]
  }
}

failed to run command: cd <project-name> && npx expo@latest install --fix
```

To fix this error, I create `.npmrc` with `legacy-peer-deps=true`, and run `npx expo@latest install --fix` again.

But, I get a new error:
```
  Render Error:

  Couldn't register the navigator. Have you wrapped your app with 'NavigatorContainer'?

  This can also happen if there are multiple copies of '@react-navigation' packages installed.
```

**Comment by dannyhw** [comment] 2024-11-14 17:45
thanks for reporting, will investigate

**Comment by dannyhw** [comment] 2024-11-14 17:48
could you share your cesconfig I didn't get the same error initially but maybe if you share the libraries you chose I can reproduce

**Comment by fredle09** [comment] 2024-11-15 03:18
Here is my `cesconfig`:

```
{
  "cesVersion": "2.11.25",
  "projectName": "demo-expo-stack-project-sdk52",
  "packages": [
    {
      "name": "expo-router",
      "type": "navigation",
      "options": {
        "type": "drawer + tabs"
      }
    },
    {
      "name": "nativewind",
      "type": "styling"
    },
    {
      "name": "supabase",
      "type": "authentication"
    }
  ],
  "flags": {
    "noGit": false,
    "noInstall": false,
    "overwrite": false,
    "importAlias": true,
    "packageManager": "npm",
    "eas": false
  },
  "packageManager": {
    "type": "npm",
    "version": "10.9.0"
  },
  "os": {
    "type": "Windows_NT",
    "platform": "win32",
    "arch": "x64",
    "kernelVersion": "10.0.22631"
  }
}
```

**Comment by dannyhw** [comment] 2024-11-18 20:05
pretty sure I found the issue #432

**Comment by RayyanNafees** [comment] 2024-11-19 07:29
Will this resolve the issue ?

I kinda have  3 hrs till the client sees the final app and I mistakenly upgraded to expo52, now even after reverting back to `expo51` this same error still stays. 

Any quickfix u guys may suggest ?

**Comment by Benoss** [comment] 2024-11-20 06:04
I just gave create-expo-stack a go and got the same issue 
Tried on node 20 and 22 and got the same error
```npx create-expo-stack@latest testapp --expo-router --drawer+tabs --nativewind --supabase --pnpm```

Have applied the fix from above but still get the same issue

![image](https://github.com/user-attachments/assets/4143732b-3e6e-4020-8d62-b8b551d5c7e1)

**Comment by rohankm** [comment] 2024-11-20 14:59
how to fix this??

**Comment by RayyanNafees** [comment] 2024-11-20 16:23
@Benoss your issue can be resolved by uninstalling `@react-navigations/native`

**Comment by dannyhw** [comment] 2024-11-20 17:01
sorry for the delay guys, just give us a bit more time theres some type errors we need to figure out from the react navigation upgrade

**Comment by dannyhw** [comment] 2024-11-25 13:08
Sorry I have a lot going on right now I haven't been able to dedicate time to this yet, will do my best to get to it.

**Comment by dannyhw** [comment] 2024-11-25 20:34
I made some adjustments to my pr hopefully it should be ready now

**Comment by blimatech** [comment] 2024-11-25 21:06
I have jus tested it and gave this error: "◒  Updating packages to expo compatible versionsError updating packages: {"stdout":"Skipped fixing dependencies: react-native-safe-area-context. These dependencies are listed in expo.install.exclude in package.json. Learn more: https://docs.expo.dev/more/expo-cli/#configuring-dependency-validation\nSkipped checking expo-router dependencies: expo-router/doctor.js not found.\n› Installing 15 SDK 52.0.0 compatible native modules using npm\n> npm install\n","status":1,"error":null}
failed to run command: cd story-shuffle && npx expo@latest install --fix"

**Comment by dannyhw** [comment] 2024-11-26 07:50
Please try again with the latest version

**Comment by Benoss** [comment] 2024-11-26 08:03
I just did a fresh install and it looks like it is working all good now

**Comment by dannyhw** [comment] 2024-11-26 10:29
I believe this was fixed now, please let us know if you run into this issue still

**Closed** 2024-11-26 10:29 UTC
